# Generated by Selenium IDE
#import pytest
import unittest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test04131(unittest.TestCase):
  def setUp(self):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def tearDown(self):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_04131(self):
    self.driver.get("https://www.baidu.com/")
    self.driver.set_window_size(550, 692)
    self.driver.find_element(By.ID, "kw").send_keys("秦牛正威")
    self.driver.find_element(By.ID, "kw").send_keys(Keys.ENTER)
    time.sleep(8)
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "秦牛正威_百度百科").click()
    
    self.vars["win6610"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win6610"])
    self.driver.execute_script("window.scrollTo(0,433)")
    element = self.driver.find_element(By.LINK_TEXT, "青春有你第二季")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "青春有你第二季").click()
    
    self.vars["win9251"] = self.wait_for_window(2000)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.switch_to.window(self.vars["win9251"])
    self.driver.execute_script("window.scrollTo(0,363.5)")
    self.driver.execute_script("window.scrollTo(0,1803.5)")
    self.driver.execute_script("window.scrollTo(0,2768)")
    self.driver.execute_script("window.scrollTo(0,3701.5)")
    self.driver.execute_script("window.scrollTo(0,3721.5)")
    self.driver.execute_script("window.scrollTo(0,3740.5)")
    self.driver.execute_script("window.scrollTo(0,3980.5)")
    self.driver.execute_script("window.scrollTo(0,3832.5)")
    self.driver.execute_script("window.scrollTo(0,4125.5)")
    self.driver.execute_script("window.scrollTo(0,3659)")
    self.driver.execute_script("window.scrollTo(0,3888)")
    self.driver.execute_script("window.scrollTo(0,4052.5)")
    self.driver.execute_script("window.scrollTo(0,4474.5)")
    self.driver.execute_script("window.scrollTo(0,4509.5)")
    self.driver.execute_script("window.scrollTo(0,4676)")
    self.driver.execute_script("window.scrollTo(0,4743.5)")
    self.driver.execute_script("window.scrollTo(0,5005)")
    self.driver.execute_script("window.scrollTo(0,5184.5)")
    self.driver.execute_script("window.scrollTo(0,5603.5)")
    self.driver.execute_script("window.scrollTo(0,6274)")
    self.driver.execute_script("window.scrollTo(0,6226)")
    self.driver.execute_script("window.scrollTo(0,6164.5)")
    self.driver.execute_script("window.scrollTo(0,6115.5)")
    self.driver.execute_script("window.scrollTo(0,6135)")
    self.driver.execute_script("window.scrollTo(0,2315)")
if __name__=="__main__":
    unittest.main()
